Bug fix: failure to fetch gating.yaml
New configuration variables were introduced, but `REMOTE_RULE_POLICIES`
was not always present. Trying to get this config param, without a
fallback will provoke this error:
TypeError: 'NoneType' object does not support item assignment
Changed the code to assume `{}` as default value.

Ref: FACTORY-5877

Signed-off-by: Giulia Naponiello <gnaponie@redhat.com>