Add missing moksha dependency
Fixes the following error:

    Traceback (most recent call last):
      File "/venv/bin/fedmsg-hub", line 8, in <module>
        sys.exit(hub())
      File "/venv/lib64/python3.9/site-packages/fedmsg/commands/hub.py", line 122, in hub
        command.execute()
      File "/venv/lib64/python3.9/site-packages/fedmsg/commands/__init__.py", line 67, in execute
        return self.run()
      File "/venv/lib64/python3.9/site-packages/fedmsg/commands/hub.py", line 94, in run
        main(
      File "/venv/lib64/python3.9/site-packages/moksha/hub/__init__.py", line 81, in main
        hub = CentralMokshaHub(config, consumers=consumers, producers=producers)
      File "/venv/lib64/python3.9/site-packages/moksha/hub/hub.py", line 270, in __init__
        super(CentralMokshaHub, self).__init__(config)
      File "/venv/lib64/python3.9/site-packages/moksha/hub/hub.py", line 125, in __init__
        self.extensions = [
      File "/venv/lib64/python3.9/site-packages/moksha/hub/hub.py", line 126, in <listcomp>
        ext(self, config) for ext in find_hub_extensions(config)
      File "/venv/lib64/python3.9/site-packages/moksha/hub/stomp/stomp.py", line 74, in __init__
        self.connect(self.addresses[self.address_index], self.key, self.crt)
      File "/venv/lib64/python3.9/site-packages/moksha/hub/stomp/stomp.py", line 83, in connect
        from twisted.internet import ssl
      File "/venv/lib64/python3.9/site-packages/twisted/internet/ssl.py", line 60, in <module>
        from OpenSSL import SSL
    ModuleNotFoundError: No module named 'OpenSSL'